## Importing Data Using Numpy

In [531]:
import numpy as np
np.set_printoptions(suppress=True,linewidth=100,precision=2)

In [532]:
raw_data_np = np.genfromtxt("C:/Users/vaibh/Downloads/loan-data.csv",delimiter=';', skip_header=1,autostrip=True)

In [533]:
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [534]:
np.isnan(raw_data_np).sum()

88005

## Filling Missing Values

In [535]:
temporary_fill=np.nanmean(raw_data_np)+1
temporary_mean=np.nanmean(raw_data_np,axis=0)

<ipython-input-535-f72135f76b53>:2: RuntimeWarning: Mean of empty slice
  temporary_mean=np.nanmean(raw_data_np,axis=0)


In [536]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [537]:
temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),temporary_mean,np.nanmax(raw_data_np,axis=0)])

<ipython-input-537-c2e4602025f4>:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),temporary_mean,np.nanmax(raw_data_np,axis=0)])


In [538]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting Dataset

### Splitting the Columns

In [539]:
column_string=np.argwhere(np.isnan(temporary_mean)).squeeze()
column_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [540]:
column_numeric=np.argwhere(np.isnan(temporary_mean)==False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [541]:
loan_data_strings = np.genfromtxt("C:/Users/vaibh/Downloads/loan-data.csv",delimiter=';', skip_header=1, usecols=column_string,dtype=np.str)
loan_data_strings

<ipython-input-541-b2580e8da163>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings = np.genfromtxt("C:/Users/vaibh/Downloads/loan-data.csv",delimiter=';', skip_header=1, usecols=column_string,dtype=np.str)


array([['May-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', ' 36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', ' 36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', ' 36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [542]:
loan_data_numeric = np.genfromtxt("C:/Users/vaibh/Downloads/loan-data.csv",delimiter=';', skip_header=1, usecols=column_numeric,filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 10394899.86,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 10394899.86,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 10394899.86, 10394899.86,     2185.64],
       [46154151.  , 10394899.86,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 10394899.86,      309.97,      301.9 ]])

In [543]:
header_full=np.genfromtxt("C:/Users/vaibh/Downloads/loan-data.csv",delimiter=';', skip_footer=raw_data_np.shape[0],autostrip=True,dtype=np.str)
header_full

<ipython-input-543-f073cdbef5f4>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  header_full=np.genfromtxt("C:/Users/vaibh/Downloads/loan-data.csv",delimiter=';', skip_footer=raw_data_np.shape[0],autostrip=True,dtype=np.str)


array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

### The Names of the Columns

In [544]:
header_string , header_numeric = header_full[column_string],header_full[column_numeric]
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [545]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue date

In [546]:
header_string[0]="issue_date"

In [547]:
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [548]:
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"-15")
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [549]:
months = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [550]:
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0] == months[i],
                           i,
                           loan_data_strings[:,0])

In [551]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan satus

In [552]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [553]:
status_good=np.array(['Current','Fully Paid', 'In Grace Period', 'Issued','Late (16-30 days)'])

In [554]:
status_bad=np.array(['','Charged Off','Default','Late (31-120 days)'])
new=loan_data_strings[:,1]
new

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [555]:
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],status_good),1,0)

In [556]:
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [557]:
np.unique(loan_data_strings[:,2])

array(['', ' 36 months', ' 60 months'], dtype='<U69')

In [558]:
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")

In [559]:
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [560]:
header_strings="term_months"

In [561]:
 loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=='',
                                '60',
                                loan_data_strings[:,2])

In [562]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [563]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [564]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=='')&(loan_data_strings[:,3]==i),
                                   i+'5',
                                   loan_data_strings[:,4])

#### Filling Subgrade

In [565]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [566]:
loan_data_strings[:,4]=np.where(loan_data_strings[:,4]=='',
                                   'H1',
                                   loan_data_strings[:,4])

In [567]:
np.unique(loan_data_strings[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [568]:
loan_data_strings

array([['5', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Deleting Grade Column

In [569]:
loan_data_strings=np.delete(loan_data_strings,3,axis=1)

In [570]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [571]:
header_string=np.delete(header_string,3)

In [572]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [573]:
keys=list(np.unique(loan_data_strings[:,3]))
values=list(range(1,loan_data_strings[:,3].shape[0]+1))
dictionary=dict(zip(keys,values))
dictionary

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [574]:
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]=np.where(loan_data_strings[:,3]==i,
                                   dictionary[i],
                                   loan_data_strings[:,3])

In [575]:
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification Status

In [576]:
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [577]:
bad_ver_status=np.array(['','Not Verified'])

In [578]:
loan_data_strings[:,4]=np.where(np.isin(loan_data_strings[:,4],bad_ver_status),0,1)

In [579]:
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

In [580]:
loan_data_strings=np.delete(loan_data_strings,5,axis=1)
header_string=np.delete(header_string,5)

In [581]:
loan_data_strings

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [582]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

### State Address

In [583]:
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [584]:
np.unique(loan_data_strings[:,5], return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [585]:
for i in np.unique(loan_data_strings[:,5]):
    loan_data_strings[:,5]=np.where(loan_data_strings[:,5]=='',
                                   0,
                                   loan_data_strings[:,5])

In [586]:
np.unique(loan_data_strings[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [587]:
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [588]:
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])

In [589]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [590]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [591]:
loan_data_strings.astype(np.int)

<ipython-input-591-8ae702ffb143>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  loan_data_strings.astype(np.int)


array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## Filling the Appropriate Values

In [592]:
temporary_stats[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

In [593]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [594]:
loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2]==temporary_fill,
                               temporary_stats[0,column_numeric[2]],
                               loan_data_numeric[:,2])

In [595]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [596]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i]=np.where(loan_data_numeric[:,i]==temporary_fill,
                               temporary_stats[2,column_numeric[i]],
                               loan_data_numeric[:,i])

In [597]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

In [598]:
header_string

array(['issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

In [609]:
loan_data_strings.shape

(10000, 6)

In [610]:
loan_data_numeric.shape

(10000, 6)

## Concatenating Numeric and String data

In [624]:
loan_data = np.hstack((loan_data_numeric,loan_data_strings))
loan_data1=loan_data

In [615]:
header_full = np.concatenate((header_numeric,header_string))

In [616]:
header_full

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'issue_date',
       'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [621]:
loan_data[np.argsort(loan_data[:,0])]

array([['12606806.0', '24975.0', '24975.0', ..., '10', '1', '2'],
       ['13026045.0', '12000.0', '12000.0', ..., '13', '1', '2'],
       ['1312426.0', '15000.0', '15000.0', ..., '16', '1', '4'],
       ...,
       ['8138291.0', '10350.0', '1000.0', ..., '26', '1', '4'],
       ['8214572.0', '7000.0', '7000.0', ..., '11', '1', '2'],
       ['849994.0', '11400.0', '11400.0', ..., '10', '0', '1']], dtype='<U69')

## Merging Header and Loan Data

In [630]:
loan_data = np.vstack((header_full,loan_data))

In [631]:
loan_data

array([['id', 'loan_amnt', 'funded_amnt', ..., 'sub_grade', 'verification_status', 'addr_state'],
       ['48010226.0', '35000.0', '35000.0', ..., '13', '1', '1'],
       ['57693261.0', '30000.0', '30000.0', ..., '5', '1', '4'],
       ...,
       ['46154151.0', '35000.0', '10000.0', ..., '17', '1', '3'],
       ['66055249.0', '10000.0', '10000.0', ..., '4', '0', '3'],
       ['id', 'loan_amnt', 'funded_amnt', ..., 'sub_grade', 'verification_status', 'addr_state']],
      dtype='<U69')

## Export the Preprocessed Dataset

In [632]:
np.savetxt("loan-data-preprocessed.csv",
          loan_data, 
          fmt="%s",
          delimiter=';')